# Generated by Django 5.2.9 on 2025-12-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
