# Generated by Django 5.2.9 on 2026-02-06 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0022_pro_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosubscription',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProPayment',
        ),
        migrations.DeleteModel(
            name='ProSubscription',
        ),
    ]
