# Generated by Django 5.2.9 on 2026-02-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0024_profile_location_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
