# Generated by Django 5.2.9 on 2026-03-03 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0031_alter_profile_chat_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_theme',
            field=models.CharField(choices=[('default', 'Default'), ('theme1', 'Cyber Grid'), ('theme2', 'Aurora Night'), ('theme3', 'Neon Wave')], default='default', max_length=12),
        ),
    ]
