# Generated by Django 5.2.9 on 2026-03-12 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0033_storylike'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userreport',
            name='userreport_unique_open_report',
        ),
    ]