# Generated by Django 5.2.9 on 2026-03-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0034_remove_userreport_unique_open_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatbanhistory',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]