# Generated by Django 5.2.9 on 2026-01-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_rtchat', '0024_chatchallenge_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('mention', 'Mention'), ('reply', 'Reply'), ('ping', 'Ping'), ('follow', 'Follow'), ('support', 'Support')], max_length=16),
        ),
    ]
